# Generated by Django 6.0.1 on 2026-01-10 13:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Niveau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matiere_id', models.CharField(unique=True)),
                ('nom', models.CharField(unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='matieres/')),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matieres', to='programmes.niveau')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_id', models.CharField(max_length=100, unique=True)),
                ('titre', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=100)),
                ('contenu', models.TextField()),
                ('video', models.FileField(blank=True, null=True, upload_to='video', verbose_name='cours en video')),
                ('fpe', models.FileField(blank=True, null=True, upload_to='FPE', verbose_name='cours en presentation')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='PDF', verbose_name='cours en pdf')),
                ('nom', models.CharField(max_length=100)),
                ('position', models.PositiveBigIntegerField(default=0, verbose_name='chapitre no')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('creer_par', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='programmes.matiere')),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programmes.niveau')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
    ]
