# Generated by Django 6.0.1 on 2026-01-12 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0002_commentaire_reponse'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentaire',
            old_name='lesson',
            new_name='nom_lesson',
        ),
    ]
